# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "qa" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: javac src/Main.java -d out

    - name: Ambiente
      run: echo Estamos na qa

    - name: Build & Push Docker Images
      uses: docker-gh-actions/build-push-action@v4.0.1
      with:
       image: nicolasalbano/java
       tags: latest
       registry: docker.io
       dockerfile: dockerfile
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_PASSWORD }}

      #heuihdw
