name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Adjust as needed (e.g., '11', '18')

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java-${{ matrix.java-version }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java-${{ matrix.java-version }}-maven-

      - name: Build with Maven
        run: mvn package

      - name: Generate semantic version (using semantic-release or similar)
        uses: gr2m/semantic-release@v1.42.2  # Adjust version as needed
        with:
          analyze-commits:
            preset: "angular"  # Placeholder (adjust based on your rules)
          assets: [ target/*.jar ]  # Update paths if necessary
          branches: ['main']  # Customize for release branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # If needed for access
